package com.chefsocial.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import com.chefsocial.model.RecipeCategory
import com.chefsocial.util.AppLanguage

data class AppStrings(
    val locale: AppLanguage = AppLanguage.RU,
    val feed: String,
    val search: String,
    val recipe: String,
    val profile: String,
    val news: String,
    val communication: String,
    val messages: String,
    val forum: String,
    val newsTitle: String,
    val newsSubtitle: String,
    val newsEmpty: String,
    val newsPinned: String,
    val newsBy: String,
    val createNews: String,
    val newsSummary: String,
    val newsBody: String,
    val publishNews: String,
    val pinNews: String,
    val adminOnly: String,
    val communicationSubtitle: String,
    val messagesEmpty: String,
    val forumEmpty: String,
    val newThread: String,
    val threadTitle: String,
    val threadBody: String,
    val createThread: String,
    val replies: String,
    val writeReply: String,
    val writeMessage: String,
    val send: String,
    val appTitle: String,
    val authWelcomeBack: String,
    val authLogin: String,
    val authRegister: String,
    val authEmail: String,
    val authPassword: String,
    val authConfirmPassword: String,
    val authForgotPassword: String,
    val authForgotPasswordHint: String,
    val authInvalidCredentials: String,
    val authFillAllFields: String,
    val authPasswordMismatch: String,
    val authPasswordTooShort: String,
    val authRegisterFailed: String,
    val feedSubtitle: String,
    val feedEmpty: String,
    val sync: String,
    val syncError: String,
    val syncSuccess: String,
    val searchTitle: String,
    val searchPlaceholder: String,
    val searchEmpty: String,
    val chefs: String,
    val recipes: String,
    val searchNothing: String,
    val newRecipe: String,
    val newRecipeHint: String,
    val gallery: String,
    val camera: String,
    val title: String,
    val description: String,
    val ingredients: String,
    val steps: String,
    val cookTime: String,
    val servings: String,
    val photoUrl: String,
    val difficulty: String,
    val easy: String,
    val medium: String,
    val hard: String,
    val publish: String,
    val myProfile: String,
    val editProfile: String,
    val saveProfile: String,
    val myRecipes: String,
    val noRecipesYet: String,
    val recipesCount: String,
    val followers: String,
    val following: String,
    val serverSync: String,
    val serverUrl: String,
    val serverToken: String,
    val saveUrl: String,
    val saveToken: String,
    val serverHint: String,
    val language: String,
    val russian: String,
    val english: String,
    val savedRecipes: String,
    val noSavedRecipes: String,
    val recipeDetail: String,
    val like: String,
    val comments: String,
    val writeComment: String,
    val ingredientsTitle: String,
    val stepsTitle: String,
    val share: String,
    val bookmark: String,
    val bookmarked: String,
    val subscribe: String,
    val unsubscribe: String,
    val leaderboard: String,
    val leaderboardSubtitle: String,
    val rank: String,
    val likes: String,
    val back: String,
    val clear: String,
    val category: String,
    val allCategories: String,
    val min: String,
    val portions: String,
    val onboardingWelcomeTitle: String,
    val onboardingWelcomeBody: String,
    val onboardingFeedTitle: String,
    val onboardingFeedBody: String,
    val onboardingShareTitle: String,
    val onboardingShareBody: String,
    val onboardingNext: String,
    val onboardingStart: String,
    val notificationChannel: String,
    val notificationNewRecipe: String,
    val notificationNewComment: String,
    val notificationNewFollower: String,
    val uploadPhoto: String,
) {
    fun categoryLabel(category: RecipeCategory): String = when (category) {
        RecipeCategory.ALL -> allCategories
        RecipeCategory.BAKING -> if (locale == AppLanguage.EN) "Baking" else "Выпечка"
        RecipeCategory.ITALIAN -> if (locale == AppLanguage.EN) "Italian" else "Итальянская"
        RecipeCategory.HEALTHY -> if (locale == AppLanguage.EN) "Healthy" else "Здоровое"
        RecipeCategory.GRILL -> if (locale == AppLanguage.EN) "Grill & BBQ" else "Гриль"
        RecipeCategory.HOME -> if (locale == AppLanguage.EN) "Home cooking" else "Домашняя"
    }

    fun difficultyLabel(value: String): String = when (value) {
        "Легко", "Easy" -> easy
        "Сложно", "Hard" -> hard
        else -> medium
    }

    companion object {
        val Russian = AppStrings(
            feed = "Лента",
            search = "Поиск",
            recipe = "Рецепт",
            profile = "Профиль",
            news = "Новости",
            communication = "Общение",
            messages = "Сообщения",
            forum = "Форум",
            newsTitle = "Новости",
            newsSubtitle = "Свежие новости от редакции Chefly",
            newsEmpty = "Пока нет новостей.\nАдмин скоро опубликует обновления.",
            newsPinned = "Закреплено",
            newsBy = "Автор",
            createNews = "Новая новость",
            newsSummary = "Краткое описание",
            newsBody = "Текст новости",
            publishNews = "Опубликовать",
            pinNews = "Закрепить",
            adminOnly = "Только для администратора",
            communicationSubtitle = "Сообщения и обсуждения",
            messagesEmpty = "Нет сообщений.\nНачните диалог с поваром из ленты.",
            forumEmpty = "Форум пуст.\nСоздайте первую тему для обсуждения.",
            newThread = "Новая тема",
            threadTitle = "Заголовок темы",
            threadBody = "Текст темы",
            createThread = "Создать тему",
            replies = "Ответы",
            writeReply = "Написать ответ…",
            writeMessage = "Сообщение…",
            send = "Отправить",
            appTitle = "Chefly",
            authWelcomeBack = "Добро пожаловать обратно",
            authLogin = "Войти",
            authRegister = "Регистрация",
            authEmail = "Email",
            authPassword = "Пароль",
            authConfirmPassword = "Повторите пароль",
            authForgotPassword = "Забыли пароль?",
            authForgotPasswordHint = "Восстановление пароля скоро появится",
            authInvalidCredentials = "Неверный email или пароль",
            authFillAllFields = "Заполните все поля",
            authPasswordMismatch = "Пароли не совпадают",
            authPasswordTooShort = "Пароль должен быть не короче 6 символов",
            authRegisterFailed = "Не удалось зарегистрироваться",
            feedSubtitle = "Свежие рецепты от поваров",
            feedEmpty = "Лента пуста.\nПодпишитесь на поваров или опубликуйте рецепт!",
            sync = "Синхронизация",
            syncError = "Ошибка синхронизации",
            syncSuccess = "Синхронизировано",
            searchTitle = "Поиск",
            searchPlaceholder = "Рецепты, ингредиенты, повара…",
            searchEmpty = "Найдите рецепт или повара\nпо имени или ингредиенту",
            chefs = "Повара",
            recipes = "Рецепты",
            searchNothing = "Ничего не найдено",
            newRecipe = "Новый рецепт",
            newRecipeHint = "Поделитесь рецептом с сообществом поваров",
            gallery = "Галерея",
            camera = "Камера",
            title = "Название",
            description = "Описание",
            ingredients = "Ингредиенты",
            steps = "Шаги приготовления",
            cookTime = "Время (мин)",
            servings = "Порций",
            photoUrl = "Фото (URL или локальный файл)",
            difficulty = "Сложность",
            easy = "Легко",
            medium = "Средне",
            hard = "Сложно",
            publish = "Опубликовать рецепт",
            myProfile = "Мой профиль",
            editProfile = "Редактировать профиль",
            saveProfile = "Сохранить",
            myRecipes = "Мои рецепты",
            noRecipesYet = "Вы ещё не опубликовали рецепты",
            recipesCount = "Рецепты",
            followers = "Подписчики",
            following = "Подписки",
            serverSync = "Синхронизация с сервером",
            serverUrl = "URL сервера",
            serverToken = "API токен (опционально)",
            saveUrl = "Сохранить URL",
            saveToken = "Сохранить токен",
            serverHint = "Запустите сервер: ./gradlew :server:run",
            language = "Язык",
            russian = "Русский",
            english = "English",
            savedRecipes = "Закладки",
            noSavedRecipes = "Нет сохранённых рецептов",
            recipeDetail = "Рецепт",
            like = "Нравится",
            comments = "Комментарии",
            writeComment = "Написать комментарий…",
            ingredientsTitle = "Ингредиенты",
            stepsTitle = "Приготовление",
            share = "Поделиться",
            bookmark = "В закладки",
            bookmarked = "В закладках",
            subscribe = "Подписаться",
            unsubscribe = "Отписаться",
            leaderboard = "Рейтинг поваров",
            leaderboardSubtitle = "Топ по лайкам и подписчикам",
            rank = "Место",
            likes = "Лайки",
            back = "Назад",
            clear = "Очистить",
            category = "Категория",
            allCategories = "Все",
            min = "мин",
            portions = "порц.",
            onboardingWelcomeTitle = "Добро пожаловать в Chefly",
            onboardingWelcomeBody = "Сообщество поваров, где делятся рецептами и вдохновением.",
            onboardingFeedTitle = "Лента рецептов",
            onboardingFeedBody = "Подписывайтесь на поваров, лайкайте и комментируйте блюда.",
            onboardingShareTitle = "Делитесь своим",
            onboardingShareBody = "Публикуйте рецепты с фото с камеры или галереи.",
            onboardingNext = "Далее",
            onboardingStart = "Начать",
            notificationChannel = "ChefSocial",
            notificationNewRecipe = "Новый рецепт в ленте",
            notificationNewComment = "Новый комментарий к рецепту",
            notificationNewFollower = "У вас новый подписчик",
            uploadPhoto = "Загрузка фото…",
        )

        val English = AppStrings(
            feed = "Feed",
            search = "Search",
            recipe = "Recipe",
            profile = "Profile",
            news = "News",
            communication = "Chat",
            messages = "Messages",
            forum = "Forum",
            newsTitle = "News",
            newsSubtitle = "Fresh updates from the Chefly team",
            newsEmpty = "No news yet.\nAdmin will publish updates soon.",
            newsPinned = "Pinned",
            newsBy = "By",
            createNews = "New article",
            newsSummary = "Summary",
            newsBody = "Article body",
            publishNews = "Publish",
            pinNews = "Pin to top",
            adminOnly = "Admin only",
            communicationSubtitle = "Messages and discussions",
            messagesEmpty = "No messages yet.\nStart a chat with a chef from the feed.",
            forumEmpty = "Forum is empty.\nCreate the first discussion topic.",
            newThread = "New topic",
            threadTitle = "Topic title",
            threadBody = "Topic text",
            createThread = "Create topic",
            replies = "Replies",
            writeReply = "Write a reply…",
            writeMessage = "Message…",
            send = "Send",
            appTitle = "Chefly",
            authWelcomeBack = "Welcome back",
            authLogin = "Log in",
            authRegister = "Sign up",
            authEmail = "Email",
            authPassword = "Password",
            authConfirmPassword = "Confirm password",
            authForgotPassword = "Forgot password?",
            authForgotPasswordHint = "Password recovery is coming soon",
            authInvalidCredentials = "Invalid email or password",
            authFillAllFields = "Fill in all fields",
            authPasswordMismatch = "Passwords do not match",
            authPasswordTooShort = "Password must be at least 6 characters",
            authRegisterFailed = "Registration failed",
            feedSubtitle = "Fresh recipes from chefs",
            feedEmpty = "Feed is empty.\nFollow chefs or publish a recipe!",
            sync = "Sync",
            syncError = "Sync error",
            syncSuccess = "Synced",
            searchTitle = "Search",
            searchPlaceholder = "Recipes, ingredients, chefs…",
            searchEmpty = "Find a recipe or chef\nby name or ingredient",
            chefs = "Chefs",
            recipes = "Recipes",
            searchNothing = "Nothing found",
            newRecipe = "New recipe",
            newRecipeHint = "Share your recipe with the chef community",
            gallery = "Gallery",
            camera = "Camera",
            title = "Title",
            description = "Description",
            ingredients = "Ingredients",
            steps = "Cooking steps",
            cookTime = "Time (min)",
            servings = "Servings",
            photoUrl = "Photo (URL or local file)",
            difficulty = "Difficulty",
            easy = "Easy",
            medium = "Medium",
            hard = "Hard",
            publish = "Publish recipe",
            myProfile = "My profile",
            editProfile = "Edit profile",
            saveProfile = "Save",
            myRecipes = "My recipes",
            noRecipesYet = "You haven't published recipes yet",
            recipesCount = "Recipes",
            followers = "Followers",
            following = "Following",
            serverSync = "Server sync",
            serverUrl = "Server URL",
            serverToken = "API token (optional)",
            saveUrl = "Save URL",
            saveToken = "Save token",
            serverHint = "Run server: ./gradlew :server:run",
            language = "Language",
            russian = "Русский",
            english = "English",
            savedRecipes = "Bookmarks",
            noSavedRecipes = "No saved recipes",
            recipeDetail = "Recipe",
            like = "Like",
            comments = "Comments",
            writeComment = "Write a comment…",
            ingredientsTitle = "Ingredients",
            stepsTitle = "Instructions",
            share = "Share",
            bookmark = "Bookmark",
            bookmarked = "Bookmarked",
            subscribe = "Follow",
            unsubscribe = "Unfollow",
            leaderboard = "Chef leaderboard",
            leaderboardSubtitle = "Top by likes and followers",
            rank = "Rank",
            likes = "Likes",
            back = "Back",
            clear = "Clear",
            category = "Category",
            allCategories = "All",
            min = "min",
            portions = "serv.",
            onboardingWelcomeTitle = "Welcome to Chefly",
            onboardingWelcomeBody = "A chef community for sharing recipes and inspiration.",
            onboardingFeedTitle = "Recipe feed",
            onboardingFeedBody = "Follow chefs, like and comment on dishes.",
            onboardingShareTitle = "Share yours",
            onboardingShareBody = "Publish recipes with photos from camera or gallery.",
            onboardingNext = "Next",
            onboardingStart = "Get started",
            notificationChannel = "ChefSocial",
            notificationNewRecipe = "New recipe in feed",
            notificationNewComment = "New comment on recipe",
            notificationNewFollower = "You have a new follower",
            uploadPhoto = "Uploading photo…",
        )

        fun forLanguage(language: AppLanguage): AppStrings =
            (if (language == AppLanguage.EN) English else Russian).copy(locale = language)
    }
}

@Composable
fun rememberAppStrings(language: AppLanguage): AppStrings =
    remember(language) { AppStrings.forLanguage(language) }
