package com.chefsocial.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import com.chefsocial.model.AppThemeMode
import com.chefsocial.model.FeedSortMode
import com.chefsocial.model.MessagePrivacy
import com.chefsocial.model.NewsType
import com.chefsocial.model.ProfileVisibility
import com.chefsocial.model.RecipeCategory
import com.chefsocial.util.AppLanguage

data class AppStrings(
    val locale: AppLanguage = AppLanguage.RU,
    val feed: String,
    val search: String,
    val recipe: String,
    val profile: String,
    val news: String,
    val communication: String,
    val messages: String,
    val forum: String,
    val newsTitle: String,
    val newsSubtitle: String,
    val newsEmpty: String,
    val newsPinned: String,
    val newsBy: String,
    val createNews: String,
    val newsSummary: String,
    val newsBody: String,
    val publishNews: String,
    val pinNews: String,
    val markNewsAsNew: String,
    val newsPhoto: String,
    val newsType: String,
    val newsNew: String,
    val allNewsTypes: String,
    val adminOnly: String,
    val communicationSubtitle: String,
    val messagesEmpty: String,
    val forumEmpty: String,
    val newThread: String,
    val threadTitle: String,
    val threadBody: String,
    val createThread: String,
    val replies: String,
    val writeReply: String,
    val writeMessage: String,
    val send: String,
    val appTitle: String,
    val authWelcomeBack: String,
    val authLogin: String,
    val authRegister: String,
    val authEmail: String,
    val authPassword: String,
    val authConfirmPassword: String,
    val authForgotPassword: String,
    val authForgotPasswordHint: String,
    val authEmailHint: String,
    val authPasswordHint: String,
    val showPassword: String,
    val hidePassword: String,
    val forgotPasswordTitle: String,
    val forgotPasswordSubtitle: String,
    val forgotPasswordContinue: String,
    val forgotPasswordNewPassword: String,
    val forgotPasswordSubmit: String,
    val forgotPasswordSuccess: String,
    val forgotPasswordUnknownEmail: String,
    val forgotPasswordBackToLogin: String,
    val onboardingSwipeHint: String,
    val authInvalidCredentials: String,
    val authFillAllFields: String,
    val authPasswordMismatch: String,
    val authPasswordTooShort: String,
    val authRegisterFailed: String,
    val feedSubtitle: String,
    val feedEmpty: String,
    val sync: String,
    val syncError: String,
    val syncSuccess: String,
    val searchTitle: String,
    val searchPlaceholder: String,
    val searchEmpty: String,
    val chefs: String,
    val recipes: String,
    val searchNothing: String,
    val newRecipe: String,
    val newRecipeHint: String,
    val gallery: String,
    val camera: String,
    val title: String,
    val description: String,
    val ingredients: String,
    val steps: String,
    val cookTime: String,
    val servings: String,
    val photoUrl: String,
    val difficulty: String,
    val easy: String,
    val medium: String,
    val hard: String,
    val publish: String,
    val myProfile: String,
    val editProfile: String,
    val saveProfile: String,
    val myRecipes: String,
    val noRecipesYet: String,
    val recipesCount: String,
    val followers: String,
    val following: String,
    val serverSync: String,
    val serverUrl: String,
    val serverToken: String,
    val saveUrl: String,
    val saveToken: String,
    val serverHint: String,
    val language: String,
    val russian: String,
    val english: String,
    val savedRecipes: String,
    val noSavedRecipes: String,
    val recipeDetail: String,
    val like: String,
    val comments: String,
    val writeComment: String,
    val ingredientsTitle: String,
    val stepsTitle: String,
    val share: String,
    val bookmark: String,
    val bookmarked: String,
    val subscribe: String,
    val unsubscribe: String,
    val leaderboard: String,
    val leaderboardSubtitle: String,
    val rank: String,
    val likes: String,
    val back: String,
    val clear: String,
    val category: String,
    val allCategories: String,
    val min: String,
    val portions: String,
    val onboardingWelcomeTitle: String,
    val onboardingWelcomeBody: String,
    val onboardingFeedTitle: String,
    val onboardingFeedBody: String,
    val onboardingShareTitle: String,
    val onboardingShareBody: String,
    val onboardingNext: String,
    val onboardingStart: String,
    val welcomeActionTitle: String,
    val welcomeActionSubtitle: String,
    val welcomeActionCreateRecipe: String,
    val welcomeActionFollowChefs: String,
    val welcomeActionSkip: String,
    val more: String,
    val notificationChannel: String,
    val notificationNewRecipe: String,
    val notificationNewComment: String,
    val notificationNewFollower: String,
    val uploadPhoto: String,
    val settings: String,
    val profileTabRecipes: String,
    val profileTabSaved: String,
    val profileTabLiked: String,
    val totalLikes: String,
    val shareProfile: String,
    val message: String,
    val pinnedRecipe: String,
    val profileLink: String,
    val pinRecipe: String,
    val publishFirstRecipe: String,
    val noLikedRecipes: String,
    val profilePrivateHint: String,
    val editPhoto: String,
    val logout: String,
    val selectEmoji: String,
    val followersTitle: String,
    val followingTitle: String,
    val username: String,
    val noFollowers: String,
    val noFollowing: String,
    val settingsAccount: String,
    val settingsNotifications: String,
    val settingsApp: String,
    val settingsSync: String,
    val settingsData: String,
    val settingsAbout: String,
    val settingsPrivacy: String,
    val settingsAdmin: String,
    val changePassword: String,
    val currentPassword: String,
    val newPassword: String,
    val passwordChanged: String,
    val passwordChangeFailed: String,
    val deleteAccount: String,
    val deleteAccountConfirm: String,
    val deleteAccountDone: String,
    val notificationsEnabled: String,
    val notifyRecipesFeed: String,
    val autoSync: String,
    val lastSync: String,
    val neverSynced: String,
    val theme: String,
    val themeLight: String,
    val themeDark: String,
    val themeSystem: String,
    val feedSort: String,
    val feedSortNewest: String,
    val feedSortPopular: String,
    val defaultCategory: String,
    val profileVisibility: String,
    val profilePublic: String,
    val profileFollowersOnly: String,
    val messagePrivacy: String,
    val messagesEveryone: String,
    val messagesFollowersOnly: String,
    val showBookmarksPublic: String,
    val storageUsed: String,
    val clearCache: String,
    val cacheCleared: String,
    val exportRecipes: String,
    val exportDone: String,
    val exportEmpty: String,
    val appVersion: String,
    val privacyPolicy: String,
    val privacyPolicyBody: String,
    val contactSupport: String,
    val manageNews: String,
    val replayOnboarding: String,
    val cancel: String,
    val confirm: String,
) {
    fun categoryLabel(category: RecipeCategory): String = when (category) {
        RecipeCategory.ALL -> allCategories
        RecipeCategory.BAKING -> if (locale == AppLanguage.EN) "Baking" else "Выпечка"
        RecipeCategory.ITALIAN -> if (locale == AppLanguage.EN) "Italian" else "Итальянская"
        RecipeCategory.HEALTHY -> if (locale == AppLanguage.EN) "Healthy" else "Здоровое"
        RecipeCategory.GRILL -> if (locale == AppLanguage.EN) "Grill & BBQ" else "Гриль"
        RecipeCategory.HOME -> if (locale == AppLanguage.EN) "Home cooking" else "Домашняя"
    }

    fun newsTypeLabel(type: NewsType): String = when (type) {
        NewsType.ALL -> allNewsTypes
        NewsType.ANNOUNCEMENT -> if (locale == AppLanguage.EN) "Announcement" else "Объявление"
        NewsType.EVENT -> if (locale == AppLanguage.EN) "Event" else "Событие"
        NewsType.TIPS -> if (locale == AppLanguage.EN) "Tips" else "Советы"
        NewsType.UPDATE -> if (locale == AppLanguage.EN) "Update" else "Обновление"
        NewsType.GENERAL -> if (locale == AppLanguage.EN) "News" else "Новости"
    }

    fun themeLabel(mode: AppThemeMode): String = when (mode) {
        AppThemeMode.LIGHT -> themeLight
        AppThemeMode.DARK -> themeDark
        AppThemeMode.SYSTEM -> themeSystem
    }

    fun feedSortLabel(mode: FeedSortMode): String = when (mode) {
        FeedSortMode.NEWEST -> feedSortNewest
        FeedSortMode.POPULAR -> feedSortPopular
    }

    fun profileVisibilityLabel(visibility: ProfileVisibility): String = when (visibility) {
        ProfileVisibility.PUBLIC -> profilePublic
        ProfileVisibility.FOLLOWERS_ONLY -> profileFollowersOnly
    }

    fun messagePrivacyLabel(privacy: MessagePrivacy): String = when (privacy) {
        MessagePrivacy.EVERYONE -> messagesEveryone
        MessagePrivacy.FOLLOWERS_ONLY -> messagesFollowersOnly
    }

    fun topChefBadge(rank: Int): String =
        if (locale == AppLanguage.EN) "Top $rank" else "Топ-$rank"

    fun profileMiniStats(recipes: Int, likes: Int): String =
        if (locale == AppLanguage.EN) {
            "$recipes recipes · $likes likes"
        } else {
            "$recipes рецептов · $likes лайков"
        }

    fun difficultyLabel(value: String): String = when (value) {
        "Легко", "Easy" -> easy
        "Сложно", "Hard" -> hard
        else -> medium
    }

    companion object {
        val Russian = AppStrings(
            feed = "Лента",
            search = "Поиск",
            recipe = "Рецепт",
            profile = "Профиль",
            news = "Новости",
            communication = "Общение",
            messages = "Сообщения",
            forum = "Форум",
            newsTitle = "Новости",
            newsSubtitle = "Свежие новости от редакции Chefly",
            newsEmpty = "Пока нет новостей.\nАдмин скоро опубликует обновления.",
            newsPinned = "Закреплено",
            newsBy = "Автор",
            createNews = "Новая новость",
            newsSummary = "Краткое описание",
            newsBody = "Текст новости",
            publishNews = "Опубликовать",
            pinNews = "Закрепить",
            markNewsAsNew = "Пометить как новую",
            newsPhoto = "Фото новости",
            newsType = "Тип новости",
            newsNew = "Новое",
            allNewsTypes = "Все",
            adminOnly = "Только для администратора",
            communicationSubtitle = "Сообщения и обсуждения",
            messagesEmpty = "Нет сообщений.\nНачните диалог с поваром из ленты.",
            forumEmpty = "Форум пуст.\nСоздайте первую тему для обсуждения.",
            newThread = "Новая тема",
            threadTitle = "Заголовок темы",
            threadBody = "Текст темы",
            createThread = "Создать тему",
            replies = "Ответы",
            writeReply = "Написать ответ…",
            writeMessage = "Сообщение…",
            send = "Отправить",
            appTitle = "Chefly",
            authWelcomeBack = "Добро пожаловать обратно",
            authLogin = "Войти",
            authRegister = "Регистрация",
            authEmail = "Email",
            authPassword = "Пароль",
            authConfirmPassword = "Повторите пароль",
            authForgotPassword = "Забыли пароль?",
            authForgotPasswordHint = "Введите email, указанный при регистрации",
            authEmailHint = "example@mail.com",
            authPasswordHint = "Минимум 6 символов",
            showPassword = "Показать пароль",
            hidePassword = "Скрыть пароль",
            forgotPasswordTitle = "Восстановление пароля",
            forgotPasswordSubtitle = "Укажите email аккаунта Chefly. Если он найден, задайте новый пароль.",
            forgotPasswordContinue = "Продолжить",
            forgotPasswordNewPassword = "Новый пароль",
            forgotPasswordSubmit = "Сохранить пароль",
            forgotPasswordSuccess = "Пароль обновлён. Войдите с новым паролем.",
            forgotPasswordUnknownEmail = "Аккаунт с таким email не найден",
            forgotPasswordBackToLogin = "Вернуться ко входу",
            onboardingSwipeHint = "Листайте влево или нажмите «Далее»",
            authInvalidCredentials = "Неверный email или пароль",
            authFillAllFields = "Заполните все поля",
            authPasswordMismatch = "Пароли не совпадают",
            authPasswordTooShort = "Пароль должен быть не короче 6 символов",
            authRegisterFailed = "Не удалось зарегистрироваться",
            feedSubtitle = "Свежие рецепты от поваров",
            feedEmpty = "Лента пуста.\nПодпишитесь на поваров или опубликуйте рецепт!",
            sync = "Синхронизация",
            syncError = "Ошибка синхронизации",
            syncSuccess = "Синхронизировано",
            searchTitle = "Поиск",
            searchPlaceholder = "Рецепты, ингредиенты, повара…",
            searchEmpty = "Найдите рецепт или повара\nпо имени или ингредиенту",
            chefs = "Повара",
            recipes = "Рецепты",
            searchNothing = "Ничего не найдено",
            newRecipe = "Новый рецепт",
            newRecipeHint = "Поделитесь рецептом с сообществом поваров",
            gallery = "Галерея",
            camera = "Камера",
            title = "Название",
            description = "Описание",
            ingredients = "Ингредиенты",
            steps = "Шаги приготовления",
            cookTime = "Время (мин)",
            servings = "Порций",
            photoUrl = "Фото (URL или локальный файл)",
            difficulty = "Сложность",
            easy = "Легко",
            medium = "Средне",
            hard = "Сложно",
            publish = "Опубликовать рецепт",
            myProfile = "Мой профиль",
            editProfile = "Редактировать профиль",
            saveProfile = "Сохранить",
            myRecipes = "Мои рецепты",
            noRecipesYet = "Вы ещё не опубликовали рецепты",
            recipesCount = "Рецепты",
            followers = "Подписчики",
            following = "Подписки",
            serverSync = "Синхронизация с сервером",
            serverUrl = "URL сервера",
            serverToken = "API токен (опционально)",
            saveUrl = "Сохранить URL",
            saveToken = "Сохранить токен",
            serverHint = "Запустите сервер: ./gradlew :server:run",
            language = "Язык",
            russian = "Русский",
            english = "English",
            savedRecipes = "Закладки",
            noSavedRecipes = "Нет сохранённых рецептов",
            recipeDetail = "Рецепт",
            like = "Нравится",
            comments = "Комментарии",
            writeComment = "Написать комментарий…",
            ingredientsTitle = "Ингредиенты",
            stepsTitle = "Приготовление",
            share = "Поделиться",
            bookmark = "В закладки",
            bookmarked = "В закладках",
            subscribe = "Подписаться",
            unsubscribe = "Отписаться",
            leaderboard = "Рейтинг поваров",
            leaderboardSubtitle = "Топ по лайкам и подписчикам",
            rank = "Место",
            likes = "Лайки",
            back = "Назад",
            clear = "Очистить",
            category = "Категория",
            allCategories = "Все",
            min = "мин",
            portions = "порц.",
            onboardingWelcomeTitle = "Добро пожаловать в Chefly",
            onboardingWelcomeBody = "Сообщество поваров, где делятся рецептами и вдохновением.",
            onboardingFeedTitle = "Лента рецептов",
            onboardingFeedBody = "Подписывайтесь на поваров, лайкайте и комментируйте блюда.",
            onboardingShareTitle = "Делитесь своим",
            onboardingShareBody = "Публикуйте рецепты с фото с камеры или галереи.",
            onboardingNext = "Далее",
            onboardingStart = "Начать",
            welcomeActionTitle = "С чего начнём?",
            welcomeActionSubtitle = "Опубликуйте первый рецепт или найдите поваров, на которых хотите подписаться.",
            welcomeActionCreateRecipe = "Создать первый рецепт",
            welcomeActionFollowChefs = "Найти поваров",
            welcomeActionSkip = "Пропустить",
            more = "Ещё",
            notificationChannel = "Chefly",
            notificationNewRecipe = "Новый рецепт в ленте",
            notificationNewComment = "Новый комментарий к рецепту",
            notificationNewFollower = "У вас новый подписчик",
            uploadPhoto = "Загрузка фото…",
            settings = "Настройки",
            profileTabRecipes = "Рецепты",
            profileTabSaved = "Закладки",
            profileTabLiked = "Понравилось",
            totalLikes = "Лайки",
            shareProfile = "Поделиться профилем",
            message = "Написать",
            pinnedRecipe = "Закреплённый рецепт",
            profileLink = "Ссылка в профиле",
            pinRecipe = "Закрепить рецепт",
            publishFirstRecipe = "Опубликовать первый рецепт",
            noLikedRecipes = "Вы ещё не лайкнули рецепты",
            profilePrivateHint = "Профиль доступен только подписчикам",
            editPhoto = "Изменить фото",
            logout = "Выйти",
            selectEmoji = "Эмодзи аватара",
            followersTitle = "Подписчики",
            followingTitle = "Подписки",
            username = "Имя пользователя",
            noFollowers = "Пока нет подписчиков",
            noFollowing = "Вы ни на кого не подписаны",
            settingsAccount = "Аккаунт",
            settingsNotifications = "Уведомления",
            settingsApp = "Приложение",
            settingsSync = "Синхронизация",
            settingsData = "Данные",
            settingsAbout = "О приложении",
            settingsPrivacy = "Приватность",
            settingsAdmin = "Администрирование",
            changePassword = "Сменить пароль",
            currentPassword = "Текущий пароль",
            newPassword = "Новый пароль",
            passwordChanged = "Пароль изменён",
            passwordChangeFailed = "Не удалось сменить пароль",
            deleteAccount = "Удалить аккаунт",
            deleteAccountConfirm = "Удалить аккаунт и выйти? Локальные данные останутся на устройстве.",
            deleteAccountDone = "Аккаунт удалён",
            notificationsEnabled = "Уведомления",
            notifyRecipesFeed = "Новые рецепты в ленте",
            autoSync = "Автосинхронизация",
            lastSync = "Последняя синхронизация",
            neverSynced = "Ещё не синхронизировалось",
            theme = "Тема",
            themeLight = "Светлая",
            themeDark = "Тёмная",
            themeSystem = "Как в системе",
            feedSort = "Сортировка ленты",
            feedSortNewest = "Новые",
            feedSortPopular = "Популярные",
            defaultCategory = "Категория ленты по умолчанию",
            profileVisibility = "Видимость профиля",
            profilePublic = "Всем",
            profileFollowersOnly = "Только подписчикам",
            messagePrivacy = "Кто может писать",
            messagesEveryone = "Все",
            messagesFollowersOnly = "Только подписчики",
            showBookmarksPublic = "Показывать закладки в профиле",
            storageUsed = "Кэш фото",
            clearCache = "Очистить кэш",
            cacheCleared = "Кэш очищен",
            exportRecipes = "Экспорт рецептов",
            exportDone = "Экспорт готов",
            exportEmpty = "Нет рецептов для экспорта",
            appVersion = "Версия",
            privacyPolicy = "Политика конфиденциальности",
            privacyPolicyBody = "Chefly хранит данные локально на вашем устройстве. Email и пароль используются только для входа в приложение. Фото рецептов и профиля сохраняются на устройстве и при синхронизации отправляются на указанный вами сервер. Мы не передаём данные третьим лицам без вашего согласия.",
            contactSupport = "Написать в поддержку",
            manageNews = "Управление новостями",
            replayOnboarding = "Показать обучение снова",
            cancel = "Отмена",
            confirm = "Подтвердить",
        )

        val English = AppStrings(
            feed = "Feed",
            search = "Search",
            recipe = "Recipe",
            profile = "Profile",
            news = "News",
            communication = "Chat",
            messages = "Messages",
            forum = "Forum",
            newsTitle = "News",
            newsSubtitle = "Fresh updates from the Chefly team",
            newsEmpty = "No news yet.\nAdmin will publish updates soon.",
            newsPinned = "Pinned",
            newsBy = "By",
            createNews = "New article",
            newsSummary = "Summary",
            newsBody = "Article body",
            publishNews = "Publish",
            pinNews = "Pin to top",
            markNewsAsNew = "Mark as new",
            newsPhoto = "News photo",
            newsType = "News type",
            newsNew = "New",
            allNewsTypes = "All",
            adminOnly = "Admin only",
            communicationSubtitle = "Messages and discussions",
            messagesEmpty = "No messages yet.\nStart a chat with a chef from the feed.",
            forumEmpty = "Forum is empty.\nCreate the first discussion topic.",
            newThread = "New topic",
            threadTitle = "Topic title",
            threadBody = "Topic text",
            createThread = "Create topic",
            replies = "Replies",
            writeReply = "Write a reply…",
            writeMessage = "Message…",
            send = "Send",
            appTitle = "Chefly",
            authWelcomeBack = "Welcome back",
            authLogin = "Log in",
            authRegister = "Sign up",
            authEmail = "Email",
            authPassword = "Password",
            authConfirmPassword = "Confirm password",
            authForgotPassword = "Forgot password?",
            authForgotPasswordHint = "Enter the email you used to register",
            authEmailHint = "example@mail.com",
            authPasswordHint = "At least 6 characters",
            showPassword = "Show password",
            hidePassword = "Hide password",
            forgotPasswordTitle = "Reset password",
            forgotPasswordSubtitle = "Enter your Chefly account email. If found, set a new password.",
            forgotPasswordContinue = "Continue",
            forgotPasswordNewPassword = "New password",
            forgotPasswordSubmit = "Save new password",
            forgotPasswordSuccess = "Password updated. Sign in with your new password.",
            forgotPasswordUnknownEmail = "No account found for this email",
            forgotPasswordBackToLogin = "Back to sign in",
            onboardingSwipeHint = "Swipe left or tap Next",
            authInvalidCredentials = "Invalid email or password",
            authFillAllFields = "Fill in all fields",
            authPasswordMismatch = "Passwords do not match",
            authPasswordTooShort = "Password must be at least 6 characters",
            authRegisterFailed = "Registration failed",
            feedSubtitle = "Fresh recipes from chefs",
            feedEmpty = "Feed is empty.\nFollow chefs or publish a recipe!",
            sync = "Sync",
            syncError = "Sync error",
            syncSuccess = "Synced",
            searchTitle = "Search",
            searchPlaceholder = "Recipes, ingredients, chefs…",
            searchEmpty = "Find a recipe or chef\nby name or ingredient",
            chefs = "Chefs",
            recipes = "Recipes",
            searchNothing = "Nothing found",
            newRecipe = "New recipe",
            newRecipeHint = "Share your recipe with the chef community",
            gallery = "Gallery",
            camera = "Camera",
            title = "Title",
            description = "Description",
            ingredients = "Ingredients",
            steps = "Cooking steps",
            cookTime = "Time (min)",
            servings = "Servings",
            photoUrl = "Photo (URL or local file)",
            difficulty = "Difficulty",
            easy = "Easy",
            medium = "Medium",
            hard = "Hard",
            publish = "Publish recipe",
            myProfile = "My profile",
            editProfile = "Edit profile",
            saveProfile = "Save",
            myRecipes = "My recipes",
            noRecipesYet = "You haven't published recipes yet",
            recipesCount = "Recipes",
            followers = "Followers",
            following = "Following",
            serverSync = "Server sync",
            serverUrl = "Server URL",
            serverToken = "API token (optional)",
            saveUrl = "Save URL",
            saveToken = "Save token",
            serverHint = "Run server: ./gradlew :server:run",
            language = "Language",
            russian = "Русский",
            english = "English",
            savedRecipes = "Bookmarks",
            noSavedRecipes = "No saved recipes",
            recipeDetail = "Recipe",
            like = "Like",
            comments = "Comments",
            writeComment = "Write a comment…",
            ingredientsTitle = "Ingredients",
            stepsTitle = "Instructions",
            share = "Share",
            bookmark = "Bookmark",
            bookmarked = "Bookmarked",
            subscribe = "Follow",
            unsubscribe = "Unfollow",
            leaderboard = "Chef leaderboard",
            leaderboardSubtitle = "Top by likes and followers",
            rank = "Rank",
            likes = "Likes",
            back = "Back",
            clear = "Clear",
            category = "Category",
            allCategories = "All",
            min = "min",
            portions = "serv.",
            onboardingWelcomeTitle = "Welcome to Chefly",
            onboardingWelcomeBody = "A chef community for sharing recipes and inspiration.",
            onboardingFeedTitle = "Recipe feed",
            onboardingFeedBody = "Follow chefs, like and comment on dishes.",
            onboardingShareTitle = "Share yours",
            onboardingShareBody = "Publish recipes with photos from camera or gallery.",
            onboardingNext = "Next",
            onboardingStart = "Get started",
            welcomeActionTitle = "What would you like to do first?",
            welcomeActionSubtitle = "Publish your first recipe or discover chefs to follow.",
            welcomeActionCreateRecipe = "Create your first recipe",
            welcomeActionFollowChefs = "Discover chefs",
            welcomeActionSkip = "Skip for now",
            more = "More",
            notificationChannel = "Chefly",
            notificationNewRecipe = "New recipe in feed",
            notificationNewComment = "New comment on recipe",
            notificationNewFollower = "You have a new follower",
            uploadPhoto = "Uploading photo…",
            settings = "Settings",
            profileTabRecipes = "Recipes",
            profileTabSaved = "Saved",
            profileTabLiked = "Liked",
            totalLikes = "Likes",
            shareProfile = "Share profile",
            message = "Message",
            pinnedRecipe = "Pinned recipe",
            profileLink = "Profile link",
            pinRecipe = "Pin recipe",
            publishFirstRecipe = "Publish your first recipe",
            noLikedRecipes = "You haven't liked any recipes yet",
            profilePrivateHint = "This profile is for followers only",
            editPhoto = "Change photo",
            logout = "Log out",
            selectEmoji = "Avatar emoji",
            followersTitle = "Followers",
            followingTitle = "Following",
            username = "Username",
            noFollowers = "No followers yet",
            noFollowing = "Not following anyone yet",
            settingsAccount = "Account",
            settingsNotifications = "Notifications",
            settingsApp = "App",
            settingsSync = "Sync",
            settingsData = "Data",
            settingsAbout = "About",
            settingsPrivacy = "Privacy",
            settingsAdmin = "Administration",
            changePassword = "Change password",
            currentPassword = "Current password",
            newPassword = "New password",
            passwordChanged = "Password changed",
            passwordChangeFailed = "Could not change password",
            deleteAccount = "Delete account",
            deleteAccountConfirm = "Delete account and log out? Local data will remain on this device.",
            deleteAccountDone = "Account deleted",
            notificationsEnabled = "Notifications",
            notifyRecipesFeed = "New recipes in feed",
            autoSync = "Auto sync",
            lastSync = "Last sync",
            neverSynced = "Not synced yet",
            theme = "Theme",
            themeLight = "Light",
            themeDark = "Dark",
            themeSystem = "System",
            feedSort = "Feed sort",
            feedSortNewest = "Newest",
            feedSortPopular = "Popular",
            defaultCategory = "Default feed category",
            profileVisibility = "Profile visibility",
            profilePublic = "Everyone",
            profileFollowersOnly = "Followers only",
            messagePrivacy = "Who can message you",
            messagesEveryone = "Everyone",
            messagesFollowersOnly = "Followers only",
            showBookmarksPublic = "Show bookmarks on profile",
            storageUsed = "Photo cache",
            clearCache = "Clear cache",
            cacheCleared = "Cache cleared",
            exportRecipes = "Export recipes",
            exportDone = "Export ready",
            exportEmpty = "No recipes to export",
            appVersion = "Version",
            privacyPolicy = "Privacy policy",
            privacyPolicyBody = "Chefly stores data locally on your device. Email and password are used only for app sign-in. Recipe and profile photos are stored on device and sent to your configured sync server. We do not share data with third parties without your consent.",
            contactSupport = "Contact support",
            manageNews = "Manage news",
            replayOnboarding = "Show onboarding again",
            cancel = "Cancel",
            confirm = "Confirm",
        )

        fun forLanguage(language: AppLanguage): AppStrings =
            (if (language == AppLanguage.EN) English else Russian).copy(locale = language)
    }
}

@Composable
fun rememberAppStrings(language: AppLanguage): AppStrings =
    remember(language) { AppStrings.forLanguage(language) }
